name: Despliegue - EcomerFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Create .env
        run: |
          rm -rf .env
          touch .env
          echo "ECOMERCE_API_URL=${{ secrets.ECOMERCE_API_URL }}" > .env
          echo "ECOMERCE_TOKEN=${{ secrets.ECOMERCE_TOKEN }}" >> .env
          cd ..
      - name: Zip project ecomerce
        run: |
          cd ..
          zip -r ecomerce.zip ecomerce -x "*.git*" "*node_modules*" "*.github*" "*.vscode-upload.json" "*.DS_Store" "*.gitignore"
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Save and backup of old frontend
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          sudo rm -rf /home/proyet/ecomerce.zip || true
          sudo rm -rf /home/proyet/ecomerce/node_modules || true
          mv /home/proyet/ecomerce /home/proyet/versions/ecomerce-$(date +%Y%m%d%H%M%S) || true
          EOF

      - name: Copy project to server
        run: |
          cd ..
          scp -P ${{ secrets.SSH_PORT }} ecomerce.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/proyet
          
      - name: Unzip project frontend in server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo unzip -o /home/proyet/ecomerce.zip -d /home/proyet"
      - name: Install dependencies frontend
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/proyet/ecomerce &&  pnpm i"
      - name: Build project
        run: |
          sshpass -p ${{ secrets.SSH_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/proyet/ecomerce && pnpm run build"
      - name: Start or reload pm2 frontend
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/proyet/ecomerce && (sudo pm2 reload pm2.config.js || pm2 start pm2.config.js) && pm2 save"
